language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - pip install pytest coveralls pytest-cov pillow
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov gizeh --cov-report term-missing

after_success:
- coveralls
